//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Education
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string SecondTitle { get; set; }
        public string SecondTitle2 { get; set; }
        public string NoteSum { get; set; }
        public string Date { get; set; }
    }
}
